### PR TITLE
[7.0] In memory query cache for token repository

### PR DESCRIPTION
**Pull request by imanghafoori1**
using memoization technique on the repository to fix https://github.com/laravel/passport/issues/382

This is the most minimal solution came to my mind.

### CODE REVIEW

**Comment by taylorotwell** [comment]
No plans on adding this.

**Comment by JakeBooher** [comment]
Any particular reason why? It's currently needlessly querying the access token multiple times per request.

**Comment by driesvints** [comment]
I'll try to resubmit this later

**Comment by driesvints** [comment]
We probably don't want to put this behavior into the repository itself but solve it wherever the calls to it are made. But I can't seem to pinpoint where they're made. See https://github.com/laravel/passport/issues/382#issuecomment-528888384

**Comment by imanghafoori1** [comment]
A cleaner way to accomplish memoization way be achieved by using pipeline,
I created a package for my personal usage called laravel-middlewarize
Which does pretty good job in these situations.

**Pull request closed without merging**
