### PR TITLE
fix revoke access token when token is deleted

### PR DESCRIPTION
**Pull request by halaei**
https://github.com/laravel/passport/issues/387

### CODE REVIEW

**Comment by halaei** [comment]
This fix forces passport to return a 200 response with new tokens, instead of 500. However, I think the correct status code should be 401 and no token should be generated. This also holds when the tokens are revoked.

**Comment by halaei** [comment]
The fix is correct! If token is deleted but refresh token is still valid, the new token should be generated.

**Comment by taylorotwell** [comment]
I don't understand how this isn't the exact same code as before?

**Comment by halaei** [comment]
If find() return null, a fatal error occurs.

**Comment by taylorotwell** [comment]
Thanks

**Comment by arubacao** [comment]
Thanks @halaei . This used to produce a lot of errors in my application

pr388

@taylorotwell will you tag this or should I pull in `dev-master`?

**Pull request merged**
