### PR TITLE
Add option for using UUID client IDs (non-breaking)

### PR DESCRIPTION
**Pull request by heisian**
Introduce client UUIDs as a non-breaking change #14 

## On existing installations
- Add `Passport::useClientUUIDs()` to `app/Providers/AuthServiceProvider.php` to enable
- run `php artisan passport:uuid` to add a `uuid` column and generate UUIDs for existing clients.

## New installations
- Add `Passport::useClientUUIDs()` to `app/Providers/AuthServiceProvider.php` to enable

### CODE REVIEW

**Comment by Modelizer** [comment]
What if for those who already started using `passport` and have 100s of users?

How to migrate those users once this PR is been merged?

**Comment by taylorotwell** [comment]
I'm just not sure I see a big need for this at the moment.

**Comment by Modelizer** [comment]
It was a big step to change id to UUID. @heisian I recommend it can be discussed on stack @larachat #internals channel before submitting a PR.

**Comment by phoenixgao** [comment]
@heisian really need this, thanks for saving my day

**Comment by heisian** [comment]
Sure, just be careful with this fork.  Although unit tests all pass for it, I've not manually tested certain things like the authorization redirect. I mainly use OAuth for a stateless API, a la Github accesse tokens.

**Comment by MicroDroid** [comment]
I can't believe Taylor rejected a pull-request that adds an **optional** feature than many people want, just because he thinks it is not necessary.

**Comment by victorcastro** [comment]
@taylorotwell you have to consider. Please

**Comment by phoenixgao** [comment]
@MicroDroid Lol, how surprising! Well I could tell it's not the first time and won't be the last

**Comment by mosleim** [comment]
uuid is not working for new version?

**Comment by veelasky** [comment]
@mosleim it's not even merged.

**Comment by heisian** [comment]
You all may want to check out @ssmulders package https://github.com/ssmulders/hashed-passport

It essentially is middleware that will hash and unhash the client ID without changing the way it is stored in the database. It is a non-invasive method of handling what we want here and actually I think a better solution than what I wrote.

Use caution as always, however, I haven't tested the package myself. Cheers all!

**Comment by mohamedsharaf** [comment]
i wish if uuid is supported

**Comment by Modelizer** [comment]
@heisian don't you think so hashing and unhashing every time will put load on server?

**Comment by grEvenX** [comment]
@heisian Even @ssmulders's package doesn't cover all cases well and as long as this feature is not built-in, it will be hard to keep everything working as expected for something that seems pretty trivial to support (it can be discussed if it even should be the default as most OAuth references advice against having this as a guessable sequential number).

One case this package doesn't support is when using HTTP BASIC auth for sending client-id/client-secret (used in machine-to-machine/application context to retrieve a non-personal access token for a client) because the package relies on intercepting the request as a middleware and looking for `client_id` parameter.

**Pull request closed without merging**
