### PR TITLE
[8.x] Shouldn't the migrations use bigIncrements and indexes on relationships?

### PR DESCRIPTION
**Pull request by KieronWiltshire**
I was looking through the migrations and saw that some of them seem pretty dated and don't use bigIncrements and indexes on certain possible relationships like the `user_id` field [here][1].

[1]: https://github.com/KieronWiltshire/passport/blob/8.x/database/migrations/2016_06_01_000004_create_oauth_clients_table.php#L18

### CODE REVIEW

**Comment by driesvints** [comment]
Have you tried these changes on all four supported DB drivers? Sqlite, MySQL, PostGres & SQL Srv?

**Comment by KieronWiltshire** [comment]
@driesvints I have only tested this with MySQL, I was under the assumption that the point behind the Schema interface is that it abstracts the four supported drivers away

**Comment by driesvints** [comment]
@KieronWiltshire have you checked into how the cascading deletes affect the underlying repository code? I suspect atm the code within Passport itself is currently handling the deletion of related records etc.

**Comment by KieronWiltshire** [comment]
@driesvints I didn't see the point as I couldn't find any use cases as to where it would be damaging, for example... if a client is deleted, shouldn't access tokens etc be deleted along with? there would be no reason to keep them?

**Comment by taylorotwell** [comment]
Remove the cascading foreign key you added.

**Comment by clemblanco** [comment]
Same question for `oauth_personal_access_clients`.`client_id`?

**Pull request merged**
