### PR TITLE
[8.x] mergeConfigFrom() already check if app is running with config cached.

### PR DESCRIPTION
**Pull request by crynobone**
https://github.com/illuminate/support/blob/6.x/ServiceProvider.php#L60-L67

This solved issue with laravel/lumen-framework#938

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by lloricode** [comment]
Hi @driesvints, can you set tag with this?

Thank you

**Comment by driesvints** [comment]
@lloricode release day is today

**Comment by driesvints** [comment]
FYI: we don't officially support using Passport with Lumen. Please consider migrating to Laravel.

**Comment by Exotelis** [comment]
> FYI: we don't officially support using Passport with Lumen. Please consider migrating to Laravel.

I'd like to mention that if you just want to build an API without sessions and all these stuff, lumen is the right choice. `laravel/passwort` work perfectly with Lumen when you use the `dusterio/lumen-passport` package, even after the upgrade to 7.x

**Pull request merged**
