### PR TITLE
Token contract

### PR DESCRIPTION
**Pull request by jmosul**
Following up from laravel/passport#1073

> By using a Token interface as type hint inside the TokenRepository it allows custom Tokens to be used which is necessary when using a different database such as MongoDB as this requires the Token to extend a different base Model.
> 
> For #968

Merging into master as breaking change

### CODE REVIEW

**Comment by taylorotwell** [comment]
So, does this contract actually make sense for your Mongo implementation? Two of the methods in the interface specify an Eloquent return type.

**Comment by jmosul** [comment]
Yes, we use jenssegers/laravel-mongodb which extends the base Eloquent classes

**Comment by taylorotwell** [comment]
Honestly I think I will hold off on this for now. To me this gives an implicit promise that Passport is supposed to work with other arbitrary ORMs and even different types of databases such as NoSQL databases. I don't want to commit to providing that kind of support. Passport is a first-party Laravel package and as such is intended to work with our first-party ORM.

If you want a Mongo version of Passport I suggest forking it or creating your own version of its functionality in a way that is tuned for Mongo.

**Comment by jmosul** [comment]
I don't think it says passport supports other ORMs/databases, I think it just allows extendability.  If someone replaces Token that's their own risk. Most of Laravel is extendable this just continues in that vein.

**Pull request closed without merging**
