### PR TITLE
Customisable Authentication Model

### PR DESCRIPTION
**Pull request by gauravmak**
users provider was set statically in the code. Changed to use one specified for api configuration

### CODE REVIEW

**Comment by yokesharun** [comment]
@gauravmak 
Now i Can able to change the auth model for passport using this commit  [b582109](https://github.com/laravel/passport/commit/b582109666583b514c79f43eb84489ed0051b040) but how can i get the oauth token for those diff models?

**Comment by gauravmak** [comment]
I don't think Passport allows the selection of guard currently.

**Comment by joshmbg** [comment]
This doesn't help - you've just changed it from reading one hardcoded config section to a different hardcoded config section - it's still hardcoded!

How is this an improvement?

**Comment by andrewmclagan** [comment]
Agreed this merged PR does little to nothing to address the underlying issue of Multi-Auth.

**Comment by ErwanTouba** [comment]
First of all, thanks for this nice Oauth2 implementation.
I too would love to see a 'multi-auth' feature in laravel-passport.

**Pull request merged**
