### PR TITLE
[8.x] Allow custom routes options

### PR DESCRIPTION
**Pull request by pavinthan**
For now We couldn't provide route options to passport routes 

eg: If I enabled `MustVerifyEmail` in my app but I could not provide `verified` middleware to passport routes.

Now we can provide route options to auth passport routes like this
```
Passport::routes(function($router) {
   $router->all([
      'middleware' => ['web', 'auth', 'verified']
   ]);
});
```

Please verify the changes.

### CODE REVIEW

**Comment by JuanDMeGon** [comment]
Hello,
When you call `Passport::routes();` in your Provider, you can pass a second parameter with options, like this:

`Passport::routes(null, ['middleware' => 'verified']);`

**Comment by pavinthan** [comment]
@JuanDMeGon that applied to non authorized routes as well, if you are supply the `verified ` middleware in root options you could not authorized.

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by pavinthan** [comment]
Thanks @taylorotwell for your response and I just tried to enable `verified` middleware check in passport routes in this PR.

It's good to enable `verified` middleware check in `laravel/passport` because It's Framework's feature (MustVerifyEmail)

**Here is my story**
I have protected my application's routes with `['auth', 'verified']` middleware but that failed to work with Laravel Passport.

Users can get access token without confirming email and that token useless with `verified` routes.

**How I found it:** 
1. Create new Laravel application 
2. Wrap my application's routes into `['auth', 'verified']` middleware
3. Register new user user and It's email verification works fine 
4. Add API routes with `['auth', 'verified']` middleware
```5. Add Laravel Passport to my application and access token generation successes without verify email```
6. Also APIs routes failed to access with generated access token

please add this `verified` middleware check in `laravel/passport` in future only if you thing it's good. 

Thanks again @taylorotwell and team for greatest open sourcing, 
I ❤️ Laravel forever.

**Comment by renanwilliam** [comment]
I have created a workaround for solve this PR goal using local classes.

In `AuthServiceProvider`, using the callback function for `Passport::routes()` I will instantiate a custom class implementation of `Laravel\Passport\RouteRegistrar`:

```php
<?php
namespace App\Providers;

use App\Passport\PassportRouteCustomRegistrar;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;
use Laravel\Passport\Passport;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Passport::routes(function ($routerRegistrar) {
            $customRegistrar = new PassportRouteCustomRegistrar($routerRegistrar);
            $customRegistrar->all();
        });
    }
}

```

This custom class with extends default Passport class and can be fully customized.
```php
<?php
namespace App\Passport;

use Laravel\Passport\RouteRegistrar;

class PassportRouteCustomRegistrar extends RouteRegistrar
{
    /**
     * Create a new route registrar instance.
     *
     * @param RouteRegistrar $router
     */
    public function __construct(RouteRegistrar $router)
    {
        parent::__construct($router->router);
    }

    public function forAuthorization()
    {
        parent::forAuthorization(); // No changes are necessary
    }

    public function forAccessTokens()
    {
        parent::forAccessTokens(); // No changes are necessary
    }

    public function forTransientTokens()
    {
        parent::forTransientTokens(); // No changes are necessary
    }

    public function forClients()
    {
        $this->router->group(['middleware' => ['web', 'multiauth:api,admin,external']], function ($router) {
            $router->get('/clients', [
                'uses' => 'ClientController@forUser',
                'as' => 'passport.clients.index',
            ]);

            $router->post('/clients', [
                'uses' => 'ClientController@store',
                'as' => 'passport.clients.store',
            ]);

            $router->put('/clients/{client_id}', [
                'uses' => 'ClientController@update',
                'as' => 'passport.clients.update',
            ]);

            $router->delete('/clients/{client_id}', [
                'uses' => 'ClientController@destroy',
                'as' => 'passport.clients.destroy',
            ]);
        });
    }

    public function forPersonalAccessTokens()
    {
        $this->router->group(['middleware' => ['web', 'multiauth:api,admin,external']], function ($router) {
            $router->get('/scopes', [
                'uses' => 'ScopeController@all',
                'as' => 'passport.scopes.index',
            ]);

            $router->get('/personal-access-tokens', [
                'uses' => 'PersonalAccessTokenController@forUser',
                'as' => 'passport.personal.tokens.index',
            ]);

            $router->post('/personal-access-tokens', [
                'uses' => 'PersonalAccessTokenController@store',
                'as' => 'passport.personal.tokens.store',
            ]);

            $router->delete('/personal-access-tokens/{token_id}', [
                'uses' => 'PersonalAccessTokenController@destroy',
                'as' => 'passport.personal.tokens.destroy',
            ]);
        });
    }
}
```

This approach works fine and have no impact to default package / Laravel core.

**Pull request closed without merging**
