### PR TITLE
[9.x] Generate default cookie name from app name

### PR DESCRIPTION
**Pull request by cmorbitzer**
This implements the proposal in #981 to set the default cookie name using the app name.

I'm not sure if this should target current major version as it is a potentially breaking change.

### CODE REVIEW

**Comment by driesvints** [comment]
@cmorbitzer tests seem to be failing.

**Comment by driesvints** [comment]
Thanks for sending this in but unfortunately this is a breaking change. Every cookie name will be different for apps because it uses the app name. We should do this on master for the next release the soonest I believe.

**Comment by cmorbitzer** [comment]
@driesvints Tests pass now. I'm happy to target master; I think that's a good idea.

**Comment by taylorotwell** [comment]
Is there an actual end-user benefit to this or are we making a breaking change to soothe our own internal need for "consistency" between Laravel and Passport's cookie name generation?

**Comment by cmorbitzer** [comment]
@andriihorpenko speculated that this would eliminate most cookie override needs and I was sympathetic because I override the cookie in this way too.

As far as breaking change goes, this is pretty low impact. It’s a problem if you already use a cookie by the new name or were for some reason counting on the name being what it was. Most applications will carry on as if nothing happened and the old cookie will expire after 2 hours of disuse.

**Comment by taylorotwell** [comment]
Why do you override the cookie?

**Comment by taylorotwell** [comment]
Closing pending no answer to question above.

**Pull request closed without merging**
