### PR TITLE
[10.x] Remove Vue components

### PR DESCRIPTION
**Pull request by driesvints**

### CODE REVIEW

**Comment by geodeveloper** [comment]
May I ask why Vue components were removed? I found them very useful for quick scaffolding.

**Comment by driesvints** [comment]
We don't want to maintain them any longer. Feel free to create a package for them.

**Comment by geodeveloper** [comment]
Understandable. Thanks for your reply.

**Comment by nickpoulos** [comment]
It would be nice to add this to the Laravel 8 Passport notes or at least the Passport Upgrade guide.

**Pull request merged**
