### PR TITLE
Use Authenticatable::getAuthIdentifier() in place of Model::getKey()

### PR DESCRIPTION
**Pull request by RemiCollin**
This PR enhance interoperability by using the `Authenticatable` contract's methods when Passport require an user's identifier, thus adding the ability to use passport with custom user classes / authentication drivers.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Could be a breaking change on 5.0 branch.

**Comment by RemiCollin** [comment]
Is there a case where `$request->user()` won't return an `Authenticatable` instance ? 

That's the only breaking change I can think of and seems very unlikely to me.

**Comment by RemiCollin** [comment]
Should I target `dev-master` instead ?

**Comment by tbuteler** [comment]
@taylorotwell Do you think it's feasible to have this in 6.0? I've also bumped into this issue because we have a custom user provider in our Laravel app.

It's a potential breaking change, of course, but the likelihood of impact is low, as most Laravel implementations should have the `Authenticatable` trait in their `User` model, and by default the `getAuthIdentifier` method will return `getKey`, just like previous Passport versions.

It's worth noting that [`UserRepository::getUserEntityByUserCredentials`](https://github.com/laravel/passport/blob/6.0/src/Bridge/UserRepository.php#L58) already uses the `getAuthIdentifier` method to identify a `Bridge\User` entity, so this seems to be consistent with the existing approach.

**Pull request closed without merging**
