### PR TITLE
[11.x] Fix multi authentication provider

### PR DESCRIPTION
**Pull request by michaelnabil230**
Fix: https://github.com/laravel/passport/issues/1657

See: https://github.com/laravel/passport/pull/1656

Example application with PR: https://github.com/michaelnabil230/multi-auth-laravel-passport

### CODE REVIEW

**Comment by michaelnabil230** [comment]
@taylorotwell I created a new PR like you told me

**Comment by taylorotwell** [comment]
/
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by michaelnabil230** [comment]
@taylorotwell Told me to go and open PR for marge the code, why didn't you?

**Comment by michaelnabil230** [comment]
> @taylorotwell Told me to go and open PR for marge the code, why didn't you?

https://github.com/laravel/passport/pull/1659#issuecomment-1527332521

**Pull request closed without merging**
