### PR TITLE
Expire in 1 year by default

### PR DESCRIPTION
**Pull request by themsaid**
In reference to https://github.com/laravel/passport/issues/162 and https://github.com/laravel/passport/issues/47

100 years seems to be too long for some environments, maybe 1 year is enough?

### CODE REVIEW

**Comment by Modelizer** [comment]
Will it be a better idea to set year in `.env` file? I think this will give more flexibility for users who wants to alter.

**Comment by hinaloe** [comment]
Why the personal token limit static 1year?

**Comment by diazemiliano** [comment]
Hi guys, I've set the `expires_at` date to `one year` before now. But it seems Passport isn't checking expiration dates on `personal access tokens`. That's a default behavior? Thanks.

**Comment by MightyPork** [comment]
I found this workaround for the unfortunate fixed 1 year expiry.

After creating a token:

```
$tokenResult = $user->createToken($name);
$tokenResult->token->expires_at = Carbon::now()->addDays($expiryDays);
$tokenResult->token->save();
```

not sure who thought 1 year is enough, it's really inconvenient to have to regenerate your tokens every year.. this way, if I understand it right, you can set any arbitrary expiry period.

**Pull request merged**
