### PR TITLE
[11.x] Removed deprecated `dates` property from `AuthCode` model

### PR DESCRIPTION
**Pull request by siarheipashkevich**
Use `casts` instead of `dates` property.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Not sure we would do this on a patch release? /cc @driesvints

**Comment by siarheipashkevich** [comment]
https://github.com/laravel/passport/pull/1636

On the Laravel 10 it will break application if I use expires_at and expect that this field is carbon instance

**Comment by siarheipashkevich** [comment]
@driesvints could you check this PR please?

**Comment by driesvints** [comment]
I think this is fine tbh. I really doubt people are overwriting this directly.

**Review by driesvints — APPROVED** [review]

**Pull request merged**
